// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlq0wUJsUpaHHZxzZsoLCp5G83SEhxcU8',
    appId: '1:111109668968:web:1c5fd8fe65134dd8643bdd',
    messagingSenderId: '111109668968',
    projectId: 'covid-banten-app',
    authDomain: 'covid-banten-app.firebaseapp.com',
    storageBucket: 'covid-banten-app.firebasestorage.app',
    measurementId: 'G-SYKXPWF4HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4tIdWlldpP8e7ktNitEsZ2rl5jR-hNY',
    appId: '1:111109668968:android:f36fa3970ef72124643bdd',
    messagingSenderId: '111109668968',
    projectId: 'covid-banten-app',
    storageBucket: 'covid-banten-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyRaKLkBl68ZugXNqQxiZfWLYfB5WCoI',
    appId: '1:111109668968:ios:2925f8978884f9bd643bdd',
    messagingSenderId: '111109668968',
    projectId: 'covid-banten-app',
    storageBucket: 'covid-banten-app.firebasestorage.app',
    iosBundleId: 'com.example.covidBantenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyRaKLkBl68ZugXNqQxiZfWLYfB5WCoI',
    appId: '1:111109668968:ios:2925f8978884f9bd643bdd',
    messagingSenderId: '111109668968',
    projectId: 'covid-banten-app',
    storageBucket: 'covid-banten-app.firebasestorage.app',
    iosBundleId: 'com.example.covidBantenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlq0wUJsUpaHHZxzZsoLCp5G83SEhxcU8',
    appId: '1:111109668968:web:967d3c9539334d07643bdd',
    messagingSenderId: '111109668968',
    projectId: 'covid-banten-app',
    authDomain: 'covid-banten-app.firebaseapp.com',
    storageBucket: 'covid-banten-app.firebasestorage.app',
    measurementId: 'G-59Q97FZZZ1',
  );
}
